ReportDefinitions:
  - reportName: BirthRecordsCountReport
    summary: Count of Birth Records
    version: 1.0.0
    moduleName: rainmaker-bnd
    sourceColumns:
    - name: tenantid
      label: BND_APPL_CANT
      type: string
      source: bnd
      total: false
    - name: legacyRecords
      label: EMP_BND_LEGACYRECORDS
      type: string
      source: bnd
      total: true
    - name: nonLegacyRecords
      label: EMP_BND_NONLEGACYRECORDS
      type: string
      source: bnd
      total: true
    - name: totalRecords
      label: EMP_BND_TOTALRECORDS
      type: string
      source: bnd
      total: true
    searchParams:
    - name: fromDate
      label: BND_FROM_DATE
      type: epoch
      source: bnd
      isMandatory: false
      searchClause: AND createdtime >= $fromDate
    - name: toDate
      label: BND_TO_DATE
      type: epoch
      source: bnd
      isMandatory: false
      searchClause: AND createdtime <= $toDate  
    - name: ulb
      label: BND_APPL_CANT 
      type: singlevaluelist
      pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
      source: bnd
      wrapper: true
      isMandatory: false
      searchClause: AND tenantid = $ulb      
    query: SELECT initcap(split_part(tenantid, '.', 2)) as tenantid, COUNT(CASE WHEN createdby='import-user' THEN createdby ELSE NULL END) AS LegacyRecords, COUNT(CASE WHEN createdby!='import-user' THEN createdby ELSE NULL END) AS NonLegacyRecords, count(*) as TotalRecords FROM eg_birth_dtls where tenantid != 'pb.testing'
    groupby: GROUP BY tenantid 
    orderby: order by tenantid

  - reportName: DeathRecordsCountReport
    summary: Count of Death Records
    version: 1.0.0
    moduleName: rainmaker-bnd
    sourceColumns:
    - name: tenantid
      label: BND_APPL_CANT
      type: string
      source: bnd
      total: false
    - name: legacyRecords
      label: EMP_BND_LEGACYRECORDS
      type: string
      source: bnd
      total: true
    - name: nonLegacyRecords
      label: EMP_BND_NONLEGACYRECORDS
      type: string
      source: bnd
      total: true
    - name: totalRecords
      label: EMP_BND_TOTALRECORDS
      type: string
      source: bnd
      total: true
    searchParams:
    - name: fromDate
      label: BND_FROM_DATE
      type: epoch
      source: bnd
      isMandatory: false
      searchClause: AND createdtime >= $fromDate
    - name: toDate
      label: BND_TO_DATE
      type: epoch
      source: bnd
      isMandatory: false
      searchClause: AND createdtime <= $toDate  
    - name: ulb
      label: BND_APPL_CANT 
      type: singlevaluelist
      pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
      source: bnd
      wrapper: true
      isMandatory: false
      searchClause: AND tenantid = $ulb      
    query: SELECT initcap(split_part(tenantid, '.', 2)) as tenantid, COUNT(CASE WHEN createdby='import-user' THEN createdby ELSE NULL END) AS LegacyRecords, COUNT(CASE WHEN createdby!='import-user' THEN createdby ELSE NULL END) AS NonLegacyRecords, count(*) as TotalRecords FROM eg_death_dtls where tenantid != 'pb.testing'
    groupby: GROUP BY tenantid 
    orderby: order by tenantid
    
  - reportName: BirthRecordsCountReportCBLevel
    summary: Count of Birth Records
    version: 1.0.0
    moduleName: rainmaker-bnd
    sourceColumns:
    - name: tenantid
      label: BND_APPL_CANT
      type: string
      source: bnd
      total: false
    - name: legacyRecords
      label: EMP_BND_LEGACYRECORDS
      type: string
      source: bnd
      total: true
    - name: nonLegacyRecords
      label: EMP_BND_NONLEGACYRECORDS
      type: string
      source: bnd
      total: true
    - name: totalRecords
      label: EMP_BND_TOTALRECORDS
      type: string
      source: bnd
      total: true
    searchParams:
    - name: fromDate
      label: BND_FROM_DATE
      type: epoch
      source: bnd
      isMandatory: false
      searchClause: AND createdtime >= $fromDate
    - name: toDate
      label: BND_TO_DATE
      type: epoch
      source: bnd
      isMandatory: false
      searchClause: AND createdtime <= $toDate       
    query: SELECT initcap(split_part(tenantid, '.', 2)) as tenantid, COUNT(CASE WHEN createdby='import-user' THEN createdby ELSE NULL END) AS LegacyRecords, COUNT(CASE WHEN createdby!='import-user' THEN createdby ELSE NULL END) AS NonLegacyRecords, count(*) as TotalRecords FROM eg_birth_dtls where tenantid = $tenantid
    groupby: GROUP BY tenantid 
    orderby: order by tenantid

  - reportName: DeathRecordsCountReportCBLevel
    summary: Count of Death Records
    version: 1.0.0
    moduleName: rainmaker-bnd
    sourceColumns:
    - name: tenantid
      label: BND_APPL_CANT
      type: string
      source: bnd
      total: false
    - name: legacyRecords
      label: EMP_BND_LEGACYRECORDS
      type: string
      source: bnd
      total: true
    - name: nonLegacyRecords
      label: EMP_BND_NONLEGACYRECORDS
      type: string
      source: bnd
      total: true
    - name: totalRecords
      label: EMP_BND_TOTALRECORDS
      type: string
      source: bnd
      total: true
    searchParams:
    - name: fromDate
      label: BND_FROM_DATE
      type: epoch
      source: bnd
      isMandatory: false
      searchClause: AND createdtime >= $fromDate
    - name: toDate
      label: BND_TO_DATE
      type: epoch
      source: bnd
      isMandatory: false
      searchClause: AND createdtime <= $toDate       
    query: SELECT initcap(split_part(tenantid, '.', 2)) as tenantid, COUNT(CASE WHEN createdby='import-user' THEN createdby ELSE NULL END) AS LegacyRecords, COUNT(CASE WHEN createdby!='import-user' THEN createdby ELSE NULL END) AS NonLegacyRecords, count(*) as TotalRecords FROM eg_death_dtls where tenantid = $tenantid
    groupby: GROUP BY tenantid 
    orderby: order by tenantid
    
  - reportName: BnDPaymentReportCBLevel
    summary: Birth and Death Certificate Paid and Downloaded Records
    version: 1.0.0
    moduleName: rainmaker-bnd
    sourceColumns:
    - name: servicetype
      label: PDF_STATIC_LABEL_CONSOLIDATED_RECEIPT_SERVICE_TYPE
      type: string
      source: bnd
      total: false
    - name: receiptnumber
      label: PDF_STATIC_LABEL_CONSOLIDATED_RECEIPT_RECEIPT_NO
      type: string
      source: bnd
      total: false
    - name: paymentdate
      label: PDF_STATIC_LABEL_CONSOLIDATED_RECEIPT_PAYMENT_DATE
      type: string
      source: bnd
      total: false
    - name: consumer_code
      label: PDF_STATIC_LABEL_CONSOLIDATED_TLCERTIFICATE_APPLICATION_NO
      type: string
      source: bnd
      total: false
    - name: paidby
      label: PDF_STATIC_LABEL_CONSOLIDATED_RECEIPT_CONSUMER_NAME
      type: string
      source: bnd
      total: false
    - name: payername
      label: PDF_STATIC_LABEL_CONSOLIDATED_RECEIPT_PAYER_NAME
      type: string
      source: bnd
      total: false      
    - name: mobilenumber
      label: PDF_STATIC_LABEL_CONSOLIDATED_RECEIPT_PAYER_CONTACT
      type: string
      source: bnd
      total: false
    - name: paymentmode
      label: PDF_STATIC_LABEL_CONSOLIDATED_RECEIPT_PAYMENT_MODE
      type: string
      source: bnd
      total: false
    - name: txn_amount
      label: PDF_STATIC_LABEL_CONSOLIDATED_RECEIPT_PAID_AMOUNT
      type: string
      source: bnd
      total: false
    - name: transactionnumber
      label: PDF_STATIC_LABEL_CONSOLIDATED_RECEIPT_TRANSACTION_ID
      type: string
      source: bnd
      total: false   
    - name: bank_transaction_no
      label: PDF_STATIC_LABEL_PT_RECEIPT_BANK_TRANSACTION_NO
      type: string
      source: bnd
      total: false      
    searchParams:
    - name: fromDate
      label: PDF_STATIC_LABEL_CONSOLIDATED_PASS_LICENSE_VALIDITY_FROM
      type: epoch
      source: bnd
      isMandatory: false
      searchClause: AND pay.createdtime >= $fromDate
    - name: toDate
      label: PDF_STATIC_LABEL_CONSOLIDATED_PASS_LICENSE_VALIDITY_TO
      type: epoch
      source: bnd
      isMandatory: false
      searchClause: AND pay.createdtime <= $toDate       
    query: select CONCAT(case when paydtl.businessservice = 'BIRTH_CERT' THEN 'Birth' when paydtl.businessservice = 'DEATH_CERT' THEN 'Death' END ,' Certificate Payment Receipt') as servicetype ,paydtl.receiptnumber, To_char((To_timestamp(pay.transactiondate / 1000) at time Zone 'Asia/Kolkata'), 'DD/MM/YYYY') as paymentdate, txn.consumer_code, pay.paidby, pay.payername, pay.mobilenumber, pay.paymentmode, CAST(txn.txn_amount as text) txn_amount, pay.transactionnumber, txn.bank_transaction_no from egcl_payment pay left join egcl_paymentdetail paydtl ON paydtl.paymentid = pay.id left join eg_pg_transactions txn on txn.txn_id = pay.transactionnumber where paydtl.businessservice in ('BIRTH_CERT','DEATH_CERT') and pay.tenantid = $tenantid
    orderby: order by pay.createdtime desc    