---
ReportDefinitions:
- reportName: WaterConnectionApplicationStatusReport
  summary: Nummber of applications by there status
  version: 1.0.0
  moduleName: rainmaker-wns
  externalService:
  - entity: $.messages[*]
    apiURL: http://egov-localization:8080/localization/messages/v1/_search?locale=en_IN&tenantId=pb&module=rainmaker-ws
    keyOrder: code,message
    tableName: tbl_localization
  sourceColumns:
  - name: status
    label: report.ws.status
    type: string
    source: ws
    total: false
  - name: total
    label: report.ws.total
    type: string
    source: ws
    total: true
  searchParams:
  - name: fromDate
    label: reports.ws.fromDate
    type: epoch
    source: ws
    isMandatory: false
    searchClause: AND ws.lastmodifiedtime >= $fromDate
  - name: toDate
    label: reports.ws.toDate
    type: epoch
    source: ws
    isMandatory: false
    searchClause: AND ws.lastmodifiedtime <= $toDate
  query: SELECT COUNT(applicationno) as total,message.message as status from eg_ws_connection ws LEFT OUTER JOIN message ON split_part(message.code,'_',3) = applicationstatus AND message.locale = 'en_IN'  WHERE ws.tenantId LIKE $tenantid GROUP BY message.message
  groupby: GROUP BY message.message
  orderby: ORDER BY case message.message when 'Pending Application' then 1 when 'Pending Payment' then 2 when 'Pending Approval' then 3 when 'Approved' then 4 when 'Rejected' then 5 when 'Cancelled' then 6 else 7 end

