serviceMaps:
  serviceName: birth-death-services
  mappings:
  - version: 1.0
    description: Persists birthCertificate details in eg_birth_cert_request  table
    fromTopic: save-birth-topic
    isTransaction: true
    queryMaps:

    - query: INSERT INTO public.eg_birth_cert_request (id, birthcertificateno, createdby, createdtime, birthdtlid, filestoreid, lastmodifiedtime, lastmodifiedby, status, additionaldetail) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: birthCertificate
      jsonMaps:
      - jsonPath: $.birthCertificate.id

      - jsonPath: $.birthCertificate.birthCertificateNo

      - jsonPath: $.birthCertificate.auditDetails.createdBy

      - jsonPath: $.birthCertificate.auditDetails.createdTime

      - jsonPath: $.birthCertificate.birthDtlId

      - jsonPath: $.birthCertificate.filestoreid

      - jsonPath: $.birthCertificate.auditDetails.lastModifiedTime
      
      - jsonPath: $.birthCertificate.auditDetails.lastModifiedBy
      
      - jsonPath: $.birthCertificate.applicationStatus

      - jsonPath: $.birthCertificate.additionalDetail
        type: JSON
        dbType: JSONB


  - version: 1.0
    description: Update birthCertificate details in eg_birth_cert_request  table
    fromTopic: update-birth-topic
    isTransaction: true
    queryMaps:

    - query: INSERT INTO eg_birth_cert_request_audit SELECT * FROM eg_birth_cert_request WHERE id = ?;
      basePath: birthCertificate
      jsonMaps:
      
      - jsonPath: $.birthCertificate.id
    
    - query: UPDATE eg_birth_cert_request SET status = ?, filestoreid =?, lastmodifiedby = ?,  lastmodifiedtime = ? WHERE id=?;
      basePath: birthCertificate
      jsonMaps:
      
      - jsonPath: $.birthCertificate.applicationStatus

      - jsonPath: $.birthCertificate.filestoreid      

      - jsonPath: $.birthCertificate.auditDetails.lastModifiedBy

      - jsonPath: $.birthCertificate.auditDetails.lastModifiedTime

      - jsonPath: $.birthCertificate.id
      
      
      
  - version: 1.0
    description: Update birthCertificate details in eg_birth_cert_request  table
    fromTopic: update-birthdownload-topic
    isTransaction: true
    queryMaps:

    - query: INSERT INTO eg_birth_cert_request_audit SELECT * FROM eg_birth_cert_request WHERE id = ?;
      jsonMaps:
      
      - jsonPath: id
    
    - query: UPDATE eg_birth_cert_request SET status = ?, lastmodifiedby = ?,  lastmodifiedtime = ? WHERE birthCertificateNo=?;
      jsonMaps:
      
      - jsonPath: applicationStatus    

      - jsonPath: auditDetails.lastModifiedBy

      - jsonPath: auditDetails.lastModifiedTime

      - jsonPath: birthCertificateNo