serviceMaps:
 serviceName: lams-services
 mappings:
 - version: 1.0
   description: Persists lease renewal details in eg_lams_leaserenewal  table
   fromTopic: save-lams-lr
   isTransaction: true
   queryMaps:

       - query: INSERT INTO eg_lams_leaserenewal(id,accountid,tenantid,applicationnumber,applicationdate,action,status,createdby,lastmodifiedby,createdtime,lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
         basePath: leases.*
         jsonMaps:
          - jsonPath: $.leases.*.id

          - jsonPath: $.leases.*.accountId

          - jsonPath: $.leases.*.tenantId

          - jsonPath: $.leases.*.applicationNumber

          - jsonPath: $.leases.*.applicationDate

          - jsonPath: $.leases.*.action

          - jsonPath: $.leases.*.status

          - jsonPath: $.leases.*.auditDetails.createdBy

          - jsonPath: $.leases.*.auditDetails.lastModifiedBy

          - jsonPath: $.leases.*.auditDetails.createdTime

          - jsonPath: $.leases.*.auditDetails.lastModifiedTime



       - query: INSERT INTO eg_lams_leaserenewaldetail(id,surveyno,termno,termexpirydate,annualrent,leaserenewalid,createdby,lastmodifiedby,createdtime,lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
         basePath: leases.*.leaseDetails
         jsonMaps:
          - jsonPath: $.leases.*.leaseDetails.id

          - jsonPath: $.leases.*.leaseDetails.surveyNo

          - jsonPath: $.leases.*.leaseDetails.termno

          - jsonPath: $.leases.*.leaseDetails.termExpiryDate

          - jsonPath: $.leases.*.leaseDetails.annualRent

          - jsonPath: $.leases.*.id

          - jsonPath: $.leases.*.auditDetails.createdBy

          - jsonPath: $.leases.*.auditDetails.lastModifiedBy

          - jsonPath: $.leases.*.auditDetails.createdTime

          - jsonPath: $.leases.*.auditDetails.lastModifiedTime

