serviceMaps:
 serviceName: obm-services
 mappings:
 - version: 1.0
   description: Persists Community Hall Booking details in eg_obm_chb_dtls table
   fromTopic: save-obm-chb
   isTransaction: true
   queryMaps:

       - query: INSERT INTO eg_obm_chb_dtls(id, accountid, hallid, purpose, category, purposedescription, residenttypeid, timeslotid, tenantid, fromdate, todate, applicationnumber, applicationdate, action, status, createdby, lastmodifiedby, createdtime, lastmodifiedtime, approveddate) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
         basePath: booking
         jsonMaps:
          - jsonPath: $.booking.id

          - jsonPath: $.booking.accountId

          - jsonPath: $.booking.hallId

          - jsonPath: $.booking.purpose

          - jsonPath: $.booking.category

          - jsonPath: $.booking.purposeDescription

          - jsonPath: $.booking.residentTypeId
          
          - jsonPath: $.booking.timeSlotId
          
          - jsonPath: $.booking.tenantId

          - jsonPath: $.booking.fromDate

          - jsonPath: $.booking.toDate

          - jsonPath: $.booking.applicationNumber

          - jsonPath: $.booking.applicationDate

          - jsonPath: $.booking.action

          - jsonPath: $.booking.status

          - jsonPath: $.booking.auditDetails.createdBy

          - jsonPath: $.booking.auditDetails.lastModifiedBy

          - jsonPath: $.booking.auditDetails.createdTime

          - jsonPath: $.booking.auditDetails.lastModifiedTime

          - jsonPath: $.booking.approvedDate


       - query: INSERT INTO eg_obm_chb_bank_dtls (id, chbdtlid, accountholdername, accountnumber, nameofbank, ifsccode, accounttype, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
         basePath: booking.bankDetails
         jsonMaps:
          - jsonPath: $.booking.bankDetails.id

          - jsonPath: $.booking.id
          
          - jsonPath: $.booking.bankDetails.accountHolderName

          - jsonPath: $.booking.bankDetails.accountNumber          

          - jsonPath: $.booking.bankDetails.nameOfBank

          - jsonPath: $.booking.bankDetails.ifscCode

          - jsonPath: $.booking.bankDetails.accountType

          - jsonPath: $.booking.auditDetails.createdBy

          - jsonPath: $.booking.auditDetails.lastModifiedBy

          - jsonPath: $.booking.auditDetails.createdTime

          - jsonPath: $.booking.auditDetails.lastModifiedTime
          
          
       - query: INSERT INTO eg_obm_chb_applicationdocument( id, active, documenttype, filestoreid, chbdtlid, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
         basePath: booking.applicationDocuments.*
         jsonMaps:
          - jsonPath: $.booking.applicationDocuments.*.id

          - jsonPath: $.booking.applicationDocuments.*.active

          - jsonPath: $.booking.applicationDocuments.*.documentType

          - jsonPath: $.booking.applicationDocuments.*.fileStoreId

          - jsonPath: $.booking.id

          - jsonPath: $.booking.auditDetails.createdBy

          - jsonPath: $.booking.auditDetails.lastModifiedBy

          - jsonPath: $.booking.auditDetails.createdTime

          - jsonPath: $.booking.auditDetails.lastModifiedTime

 - version: 1.0
   description: Update CHB details
   fromTopic: update-obm-chb
   isTransaction: true
   queryMaps:

       - query: UPDATE eg_obm_chb_dtls SET approveddate = ?, action = ?, status = ?,  lastmodifiedby = ?,  lastmodifiedtime = ? WHERE id=?;
         basePath: booking
         jsonMaps:
          - jsonPath: $.booking.approvedDate

          - jsonPath: $.booking.action

          - jsonPath: $.booking.status

          - jsonPath: $.booking.auditDetails.lastModifiedBy

          - jsonPath: $.booking.auditDetails.lastModifiedTime

          - jsonPath: $.booking.id
          

       - query: UPDATE eg_obm_chb_bank_dtls SET accountholdername, accountnumber, nameofbank, ifsccode, accounttype, lastmodifiedby = ?,  lastmodifiedtime = ? WHERE id = ?;
         basePath: booking.bankDetails
         jsonMaps:
          - jsonPath: $.booking.bankDetails.accountHolderName

          - jsonPath: $.booking.bankDetails.accountNumber          

          - jsonPath: $.booking.bankDetails.nameOfBank

          - jsonPath: $.booking.bankDetails.ifscCode

          - jsonPath: $.booking.bankDetails.accountType

          - jsonPath: $.booking.auditDetails.lastModifiedBy

          - jsonPath: $.booking.auditDetails.lastModifiedTime

          - jsonPath: $.booking.bankDetails.id
          
          
       - query: INSERT INTO eg_obm_chb_applicationdocument( id, active, documenttype, filestoreid, chbdtlid, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (id) DO UPDATE SET active = ?, documenttype =?, filestoreid =?,lastmodifiedby =?, lastmodifiedtime =?;
         basePath: booking.applicationDocuments.*
         jsonMaps:
          - jsonPath: $.booking.applicationDocuments.*.id

          - jsonPath: $.booking.applicationDocuments.*.active

          - jsonPath: $.booking.applicationDocuments.*.documentType

          - jsonPath: $.booking.applicationDocuments.*.fileStoreId

          - jsonPath: $.booking.id

          - jsonPath: $.booking.auditDetails.createdBy

          - jsonPath: $.booking.auditDetails.lastModifiedBy

          - jsonPath: $.booking.auditDetails.createdTime

          - jsonPath: $.booking.auditDetails.lastModifiedTime

          - jsonPath: $.booking.applicationDocuments.*.active

          - jsonPath: $.booking.applicationDocuments.*.documentType

          - jsonPath: $.booking.applicationDocuments.*.fileStoreId

          - jsonPath: $.booking.auditDetails.lastModifiedBy

          - jsonPath: $.booking.auditDetails.lastModifiedTime
          
 - version: 1.0
   description: Update CHB details workflow
   fromTopic: update-obm-chb-workflow
   isTransaction: true
   queryMaps:

       - query: UPDATE eg_obm_chb_dtls SET approveddate = ?, action = ?, status = ?,  lastmodifiedby = ?,  lastmodifiedtime = ? WHERE id=?;
         basePath: booking
         jsonMaps:
          - jsonPath: $.booking.approvedDate

          - jsonPath: $.booking.action

          - jsonPath: $.booking.status

          - jsonPath: $.booking.auditDetails.lastModifiedBy

          - jsonPath: $.booking.auditDetails.lastModifiedTime

          - jsonPath: $.booking.id


       - query: UPDATE eg_obm_chb_bank_dtls SET lastmodifiedby = ?,  lastmodifiedtime = ? WHERE id = ?;
         basePath: booking
         jsonMaps:

          - jsonPath: $.booking.auditDetails.lastModifiedBy

          - jsonPath: $.booking.auditDetails.lastModifiedTime

          - jsonPath: $.booking.bankDetails.id
