ServiceMaps:
 serviceName: Collection Services
 version: 1.0.0
 mappings:
  - topic: egov.collection.payment-create
    configKey: INDEX
    indexes:
    - name: payindex_v1
      type: payments
      id: $.id
      isBulk: false
      timeStampField: $.auditDetails.createdTime
      jsonPath: $.Payment
      customJsonMapping:
        indexMapping: {"Data":{"businessService":"","tenantId":"","id":"","transactionNumber":"","transactionDate":1,"paymentMode":"","paymentStatus":"","payer":{"id":"","name":""},"paidBy":"","paymentDetails":{},"auditDetails":{},"additionalDetails":{},"tenantData":{},"@timestamp":"timestamp"}}
        fieldMapping:
        - inJsonPath: $.tenantId
          outJsonPath: $.Data.tenantId
        - inJsonPath: $.id
          outJsonPath: $.Data.id
        - inJsonPath: $.transactionNumber
          outJsonPath: $.Data.transactionNumber
        - inJsonPath: $.transactionDate
          outJsonPath: $.Data.transactionDate
        - inJsonPath: $.paymentMode
          outJsonPath: $.Data.paymentMode
        - inJsonPath: $.paymentStatus
          outJsonPath: $.Data.paymentStatus	
        - inJsonPath: $.payerId
          outJsonPath: $.Data.payer.id
        - inJsonPath: $.payerName
          outJsonPath: $.Data.payer.name
        - inJsonPath: $.paidBy
          outJsonPath: $.Data.paidBy
        - inJsonPath: $.paymentDetails
          outJsonPath: $.Data.paymentDetails
        - inJsonPath: $.auditDetails
          outJsonPath: $.Data.auditDetails
        - inJsonPath: $.additionalDetails
          outJsonPath: $.Data.additionalDetails
        - inJsonPath: $.@timestamp
          outJsonPath: $.Data.@timestamp
        externalUriMapping:
        - path: http://egov-localization.egov:8080/localization/messages/v1/_search
          queryParam: module=rainmaker-dss,rainmaker-uc,rainmaker-tl&locale=en_IN&tenantId=pb&codes=DSS_PGR_COMPLETION_RATE
          apiRequest: {"RequestInfo":{"apiId":"Rainmaker","ver":".01","ts":"","action":"_search","did":"1","key":"","msgId":"20170310130900|en_IN","authToken":null}}
          uriResponseMapping:
          - inJsonPath: $.messages[0].code
            outJsonPath: $.Data.businessService
        mdmsMapping:
        - path: http://egov-mdms-service.egov:8080/egov-mdms-service/v1/_search
          moduleName: tenant
          masterName: tenants
          tenantId: pb
          filter: "[?(@.code == $tenant)]"
          filterMapping:
          - variable: $tenant
            valueJsonpath: $.tenantId
          uriResponseMapping:
          - inJsonPath: $.MdmsRes.tenant.tenants
            outJsonPath: $.Data.tenantData
            
            
  - topic: egov.collection.payment-update
    configKey: INDEX
    indexes:
    - name: payindex_v1
      type: payments
      id: $.id
      isBulk: false
      timeStampField: $.auditDetails.createdTime
      jsonPath: $.Payment
      customJsonMapping:
        indexMapping: {"Data":{"businessService":"", "tenantId":"","id":"","transactionNumber":"","transactionDate":1,"paymentMode":"","paymentStatus":"","payer":{"id":"","name":""},"paidBy":"","paymentDetails":{},"auditDetails":{},"additionalDetails":{},"tenantData":{},"@timestamp":"timestamp"}}
        fieldMapping:
        - inJsonPath: $.tenantId
          outJsonPath: $.Data.tenantId
        - inJsonPath: $.id
          outJsonPath: $.Data.id
        - inJsonPath: $.transactionNumber
          outJsonPath: $.Data.transactionNumber
        - inJsonPath: $.transactionDate
          outJsonPath: $.Data.transactionDate
        - inJsonPath: $.paymentMode
          outJsonPath: $.Data.paymentMode
        - inJsonPath: $.paymentStatus
          outJsonPath: $.Data.paymentStatus
        - inJsonPath: $.payerId
          outJsonPath: $.Data.payer.id
        - inJsonPath: $.payerName
          outJsonPath: $.Data.payer.name
        - inJsonPath: $.paidBy
          outJsonPath: $.Data.paidBy
        - inJsonPath: $.paymentDetails
          outJsonPath: $.Data.paymentDetails
        - inJsonPath: $.auditDetails
          outJsonPath: $.Data.auditDetails
        - inJsonPath: $.additionalDetails
          outJsonPath: $.Data.additionalDetails
        - inJsonPath: $.@timestamp
          outJsonPath: $.Data.@timestamp
        externalUriMapping:
        - path: http://egov-localization.egov:8080/localization/messages/v1/_search
          queryParam: module=rainmaker-dss,rainmaker-uc,rainmaker-tl&locale=en_IN&tenantId=pb&codes=$.paymentDetails[0].businessService+"test"
          apiRequest: {"RequestInfo":{"apiId":"Rainmaker","ver":".01","ts":"","action":"_search","did":"1","key":"","msgId":"20170310130900|en_IN","authToken":null}}
          uriResponseMapping:
          - inJsonPath: $.messages[0].code
            outJsonPath: $.Data.businessService
        mdmsMapping:
        - path: http://egov-mdms-service.egov:8080/egov-mdms-service/v1/_search
          moduleName: tenant
          masterName: tenants
          tenantId: pb
          filter: "[?(@.code == $tenant)]"
          filterMapping:
          - variable: $tenant
            valueJsonpath: $.tenantId
          uriResponseMapping:
          - inJsonPath: $.MdmsRes.tenant.tenants
            outJsonPath: $.Data.tenantData
            
            
  - topic: egov-payment-legacy-index
    configKey: LEGACYINDEX
    indexes:
    - name: payindex_v1
      type: payments
      id: $.id
      isBulk: true
      timeStampField: $.auditDetails.createdTime
      jsonPath: $.Payments.*
      customJsonMapping:
        indexMapping: {"Data":{"tenantId":"","id":"","transactionNumber":"","transactionDate":1,"paymentMode":"","paymentStatus":"","payer":{"id":"","name":""},"paidBy":"","paymentDetails":{},"auditDetails":{},"additionalDetails":{},"tenantData":{},"@timestamp":"timestamp"}}
        fieldMapping:
        - inJsonPath: $.tenantId
          outJsonPath: $.Data.tenantId
        - inJsonPath: $.id
          outJsonPath: $.Data.id
        - inJsonPath: $.transactionNumber
          outJsonPath: $.Data.transactionNumber
        - inJsonPath: $.transactionDate
          outJsonPath: $.Data.transactionDate
        - inJsonPath: $.paymentMode
          outJsonPath: $.Data.paymentMode
        - inJsonPath: $.paymentStatus
          outJsonPath: $.Data.paymentStatus
        - inJsonPath: $.payerId
          outJsonPath: $.Data.payer.id
        - inJsonPath: $.payerName
          outJsonPath: $.Data.payer.name
        - inJsonPath: $.paidBy
          outJsonPath: $.Data.paidBy
        - inJsonPath: $.paymentDetails
          outJsonPath: $.Data.paymentDetails
        - inJsonPath: $.auditDetails
          outJsonPath: $.Data.auditDetails
        - inJsonPath: $.additionalDetails
          outJsonPath: $.Data.additionalDetails
        - inJsonPath: $.@timestamp
          outJsonPath: $.Data.@timestamp
        mdmsMapping:
        - path: http://egov-mdms-service.egov:8080/egov-mdms-service/v1/_search
          moduleName: tenant
          masterName: tenants
          tenantId: pb
          filter: "[?(@.code == $tenant)]"
          filterMapping:
          - variable: $tenant
            valueJsonpath: $.tenantId
          uriResponseMapping:
          - inJsonPath: $.MdmsRes.tenant.tenants
            outJsonPath: $.Data.tenantData
