ServiceMaps:
 serviceName: Birth Certificate Download
 version: 1.0.0
 mappings:
  - topic: save-birth-topic
    configKey: INDEX
    indexes:
      - name: birth-cert-v1
        type: general
        id: $.id
        jsonPath: $.birthCertificate
        customJsonMapping:
          indexMapping: {"Data":{}}
          fieldMapping:
          - inJsonPath: $
            outJsonPath: $.Data
  
  - topic: update-birth-topic
    configKey: INDEX
    indexes:
      - name: birth-cert-v1
        type: general
        id: $.id
        jsonPath: $.birthCertificate
        customJsonMapping:
          indexMapping: {"Data":{}}
          fieldMapping:
          - inJsonPath: $
            outJsonPath: $.Data
