ServiceMaps:
 serviceName: Birth Certificate Download
 version: 1.0.0
 mappings:
  - topic: save-birth-topic
    configKey: INDEX
    indexes:
      - name: birth-cert-v1
        type: general
        id: $.id
        jsonPath: $.birthCertificate
        customJsonMapping:
          indexMapping: {"Data":{}}
          fieldMapping:
          - inJsonPath: $.birthCertificateNo
            outJsonPath: $.Data.birthCertificateNo
          - inJsonPath: $.filestoreid
            outJsonPath: $.Data.filestoreid          
          - inJsonPath: $.birthDtlId
            outJsonPath: $.Data.birthDtlId
          - inJsonPath: $.additionalDetail
            outJsonPath: $.Data.additionalDetail
          - inJsonPath: $.applicationStatus
            outJsonPath: $.Data.applicationStatus            
          - inJsonPath: $.dateofissue
            outJsonPath: $.Data.dateofissue
          - inJsonPath: $.dateofissue
            outJsonPath: $.Data.dateofissue
          - inJsonPath: $.tenantId
            outJsonPath: $.Data.tenantId
          - inJsonPath: $.id
            outJsonPath: $.Data.id
          - inJsonPath: $.embeddedUrl
            outJsonPath: $.Data.embeddedUrl
          - inJsonPath: $.auditDetails
            outJsonPath: $.Data.auditDetails

  - topic: update-birth-topic
    configKey: INDEX
    indexes:
      - name: birth-cert-v1
        type: general
        id: $.id
        jsonPath: $.birthCertificate
        customJsonMapping:
          indexMapping: {"Data":{}}
          fieldMapping:
          - inJsonPath: $.birthCertificateNo
            outJsonPath: $.Data.birthCertificateNo
          - inJsonPath: $.filestoreid
            outJsonPath: $.Data.filestoreid          
          - inJsonPath: $.birthDtlId
            outJsonPath: $.Data.birthDtlId
          - inJsonPath: $.additionalDetail
            outJsonPath: $.Data.additionalDetail
          - inJsonPath: $.applicationStatus
            outJsonPath: $.Data.applicationStatus            
          - inJsonPath: $.dateofissue
            outJsonPath: $.Data.dateofissue
          - inJsonPath: $.dateofissue
            outJsonPath: $.Data.dateofissue
          - inJsonPath: $.tenantId
            outJsonPath: $.Data.tenantId
          - inJsonPath: $.id
            outJsonPath: $.Data.id
          - inJsonPath: $.embeddedUrl
            outJsonPath: $.Data.embeddedUrl
          - inJsonPath: $.auditDetails
            outJsonPath: $.Data.auditDetails